// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF8aPUTPc5uBBq1f_TfmQn8cbaFlTZIvU',
    appId: '1:37698152885:web:56bcdc3d1d064308fcd1fc',
    messagingSenderId: '37698152885',
    projectId: 'instagram-clone-2638c',
    authDomain: 'instagram-clone-2638c.firebaseapp.com',
    storageBucket: 'instagram-clone-2638c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuIQPwiF4p90InC0dWIqt-C_wM0RyX_Ik',
    appId: '1:37698152885:android:944903798e8d9ec7fcd1fc',
    messagingSenderId: '37698152885',
    projectId: 'instagram-clone-2638c',
    storageBucket: 'instagram-clone-2638c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpz2t8czqWgsO9ZTCd1r9umNYJMX0z2HY',
    appId: '1:37698152885:ios:fdf049d54d8f0b06fcd1fc',
    messagingSenderId: '37698152885',
    projectId: 'instagram-clone-2638c',
    storageBucket: 'instagram-clone-2638c.appspot.com',
    iosClientId: '37698152885-ig5tm9ksvbvno6hs9rum2hgnnep2dis3.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
